#!/usr/bin/env python3
"""Regenerate src/image_golden.inc from the Python port's preprocessing.

The Python preprocessing is held against transformers' Qwen2VLImageProcessor
(identical pixels, values within one fp32 ULP). This pins the C++ port to the
Python one BIT FOR BIT: for each test picture it records the grid and an FNV-1a
hash of the float32 patch tensor, which tests.cpp recomputes.

Run from the cpp/ directory:

    python3 tools/gen_image_golden.py > src/image_golden.inc
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "..", "python"))

import mlx.core as mx  # noqa: E402
import vision  # noqa: E402

DATA = os.path.join(HERE, "..", "..", "testdata")

# (file, max_pixels): the default cap, plus caps that force a downscale; the
# small pictures are upscaled to MIN_PIXELS either way.
CASES = [
    ("shapes.png", vision.MAX_PIXELS),
    ("shapes.png", 100_000),
    ("arrow_exif6.jpg", vision.MAX_PIXELS),
    ("arrow_exif6.jpg", 70_000),
    ("alpha_text.png", vision.MAX_PIXELS),
    ("gray.png", vision.MAX_PIXELS),
]


def fnv1a64(data: bytes) -> int:
    h = 0xCBF29CE484222325
    for b in data:
        h ^= b
        h = (h * 0x100000001B3) & 0xFFFFFFFFFFFFFFFF
    return h


def main():
    w = sys.stdout.write
    w("// GENERATED by tools/gen_image_golden.py from the Python port -- do not edit.\n")
    w("// Grid and FNV-1a hash of the float32 patch tensor for each test picture.\n\n")
    w("static const ImageGolden kImageGolden[] = {\n")
    for f, maxp in CASES:
        img = vision.load_image(os.path.join(DATA, f), max_pixels=maxp)
        px = img.pixels.astype(mx.float32)
        mx.eval(px)
        h = fnv1a64(bytes(memoryview(px)))
        _, gh, gw = img.grid
        w(f'    {{"{f}", {maxp}LL, {gh}, {gw}, 0x{h:016X}ULL}},\n')
    w("};\n")


if __name__ == "__main__":
    main()
