#!/usr/bin/env python3
"""Generate src/unicode_tables.cpp -- the character classes the tokenizer needs.

The pre-tokenizer splits on \\p{L}, \\p{N}, \\p{M} and \\s. Getting those
boundaries even slightly wrong changes token boundaries, which changes the ids,
which changes the model's output -- so the tables are generated from the SAME
source the verified Python implementation used (`unicodedata`) rather than
approximated from CoreFoundation's character sets, which do not line up:
kCFCharacterSetLetter is L*+M* (not pure L) and kCFCharacterSetDecimalDigit is
Nd only (not Nd+Nl+No).

`is_space` reproduces tokenizer.py's `ch.isspace() or category(ch)[0] == "Z"`
exactly, including the C1 controls 0x1C-0x1F that Rust's \\s does not match.

Run from the cpp/ directory:  python3 tools/gen_unicode.py
Committed output means the build itself needs no Python.
"""

import sys
import unicodedata

MAX_CP = 0x110000


def ranges(pred):
    """Collapse the codepoints satisfying `pred` into sorted [lo, hi] ranges."""
    out = []
    lo = None
    for cp in range(MAX_CP):
        if pred(cp):
            if lo is None:
                lo = cp
        elif lo is not None:
            out.append((lo, cp - 1))
            lo = None
    if lo is not None:
        out.append((lo, MAX_CP - 1))
    return out


def cat(cp):
    return unicodedata.category(chr(cp))


def main():
    tables = {
        "L": ranges(lambda cp: cat(cp)[0] == "L"),
        "N": ranges(lambda cp: cat(cp)[0] == "N"),
        "M": ranges(lambda cp: cat(cp)[0] == "M"),
        # tokenizer.py: ch.isspace() or category[0] == "Z"
        "SPACE": ranges(lambda cp: chr(cp).isspace() or cat(cp)[0] == "Z"),
    }

    w = sys.stdout.write
    w("// GENERATED by tools/gen_unicode.py -- do not edit.\n")
    w(f"// Unicode {unicodedata.unidata_version}\n\n")
    w('#include "unicode.hpp"\n\n')
    w("namespace uni {\n\n")
    for name, rs in tables.items():
        w(f"// {len(rs)} ranges\n")
        w(f"const Range k{name}[] = {{\n")
        for i in range(0, len(rs), 6):
            chunk = rs[i:i + 6]
            w("    " + " ".join(f"{{0x{a:X},0x{b:X}}}," for a, b in chunk) + "\n")
        w("};\n")
        w(f"const int k{name}Count = {len(rs)};\n\n")
    w("}  // namespace uni\n")

    for name, rs in tables.items():
        print(f"// {name}: {len(rs)} ranges", file=sys.stderr)


if __name__ == "__main__":
    main()
